### ISSUE TITLE
你今天explosion了嗎?

### ISSUE THREAD

**Issue by VagrantPi** [m85091081/asciiartcollection#7]
\惠惠/\惠惠/\惠惠/\惠惠/\惠惠/\惠惠/\惠惠/\惠惠/\惠惠/\惠惠/
--為美好的世界獻上祝福
能幫忙讓惠惠出現在我terminal嗎?

**Comment by dd-han** [comment]
我們需要ASCII Art文字檔支援，如果PTT尚能找到適合的圖片然後作者同意讓我們放上來，歡迎告訴我們XDD

**Comment by dd-han** [comment]
最近在學爆裂魔法，等我學玩來做

**Comment by dd-han** [comment]
我找到圖了耶，正在問作者可不可以用wwwwwwww

**Comment by dd-han** [comment]
作者同意，放上去了～～～～
