### ISSUE TITLE
加入你需要的內容、或是刪除不需要的內容吧！     預設是用vim嗎？

### ISSUE THREAD

**Issue by VagrantPi** [m85091081/asciiartcollection#8]
我有幾台最小安裝的CentOS
在“加入你需要的內容、或是刪除不需要的內容吧！”時都不會跑出編輯器
導致後續安裝好像有些BUG
所以爬了一下ASCIIArtInstaller.sh
是不是改成vi會更通用了？

**Comment by dd-han** [comment]
修正了
